name: release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.actor }}/squid
          tag_with_ref: true
