name: scan

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    name: scan
    runs-on: ubuntu-20.04
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/${{ github.actor }}/squid:latest
          format: table
          severity: HIGH,CRITICAL
